version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: network
      POSTGRES_USER: rodrigo
      POSTGRES_PASSWORD: rodrigo

  redis:
    image: redis

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
