version: '3'

services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: "rodrigo"
        ports:
            - "5432:5432"

    web:
        build: .
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"
        depends_on:
            - db  # Web service depends on the db service being up first
