# Generated by Django 5.0.2 on 2024-03-03 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_userprofile_following_alter_userprofile_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='following',
        ),
    ]
