# Generated by Django 5.0.2 on 2024-03-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_delete_watchlistitem'),
        ('network', '0007_userprofile_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(related_name='watchlist_users', to='auctions.auctionlisting'),
        ),
    ]
