# Generated by Django 5.0.2 on 2024-03-04 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_watchlistitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WatchlistItem',
        ),
    ]
