# Generated by Django 5.0.2 on 2024-03-07 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_delete_watchlistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='auctionlisting',
            name='start_time',
        ),
    ]
