name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Django unit tests
      run: |
        pip3 install --user django
        python3 manage.py test network
        python3 manage.py test mail
        python3 manage.py test auctions
        python3 manage.py test network.test_views
        python3 manage.py test mail.test_views
        python3 manage.py test auctions.test_views