name: Unit Testing

on: push
  
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Run Django unit tests
      run: |
        pip3 install --user django
        
        # Generate a unique identifier for the test database name
        TEST_DB_NAME="test_network_$RANDOM"
        
        # Run tests using the unique test database name
        python3 manage.py test network --test-name-pattern="test_*.py" --keepdb --settings=settings.test --database="$TEST_DB_NAME"
        python3 manage.py test mail --test-name-pattern="test_*.py" --keepdb --settings=settings.test --database="$TEST_DB_NAME"
        python3 manage.py test auctions --test-name-pattern="test_*.py" --keepdb --settings=settings.test --database="$TEST_DB_NAME"
        python3 manage.py test network.test_views --test-name-pattern="test_*.py" --keepdb --settings=settings.test --database="$TEST_DB_NAME"
        python3 manage.py test network.test_thread --test-name-pattern="test_*.py" --keepdb --settings=settings.test --database="$TEST_DB_NAME"
        python3 manage.py test mail.test_views --test-name-pattern="test_*.py" --keepdb --settings=settings.test --database="$TEST_DB_NAME"
        python3 manage.py test auctions.test_views --test-name-pattern="test_*.py" --keepdb --settings=settings.test --database="$TEST_DB_NAME"
