name: Unit Testing

on: push
  
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: rodrigo
          POSTGRES_PASSWORD: rodrigo
          POSTGRES_DB: network
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Run Django unit tests
      run: |
        pip3 install --user django
        python3 manage.py test network
        python3 manage.py test mail
        python3 manage.py test auctions
        python3 manage.py test network.test_views
        python3 manage.py test mail.test_views
        python3 manage.py test auctions.test_views
